services:
  - type: web
    name: deezer-splitter
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8080
    disk:
      name: uploads
      mountPath: /app/public
      sizeGB: 1